baseURL = "https://samharrison.science"
title = "Sam Harrison"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Sam Harrison"
description = "Sam Harrison - Research scientist of UKCEH, specialising in environmental modelling and software sustainability"
keywords = "environmental scientist,environmental modelling,research software,blog"
info = ["Research scientist at UKCEH, specialising in environmental contaminant modelling and software sustainability. Frequent fell runner, mountain climber and cyclist. Occasional violinist, pianist and guitarist."]
avatarURL = "images/sam.jpg"
dateFormat = "2 January 2006"
favicon_32 = "images/favicon32.png"
favicon_64 = "images/favicon64.png"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/samharrison7/samharrison-hugo/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = ['scss/override.scss']
# Custom JS
customJS = []
# Use KaTeX
katex = true

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-75Q9R37970"

[params.utterances]
repo = "samharrison7/samharrison-hugo"
issueTerm = "pathname"
label = "comment"
theme = "preferred-color-scheme"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'", "https://utteranc.es"]
imgsrc = ["'self'", "https://storage.ko-fi.com"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com",
             "https://storage.ko-fi.com", "https://cdn.jsdelivr.net", "https://utteranc.es",
             "https://www.googletagmanager.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com", "https://www.googletagmanager.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
# author = "authors"
output = "outputs"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/samharrison7/"

# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-2x fa-gitlab"
# weight = 2
# url = "https://gitlab.com/samharrison7/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/samharrison7/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/samharrison7/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://samharrison.science/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "My Research"
weight = 1
url = "my-research/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"


[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[markup]
  [markup.highlight]
    style = "autumn"
  [markup.goldmark.renderer]
    unsafe = true